title = "MH Bathymetry Reco setup"

[simulation]
xbounds = [1.5, 15.0]
timestep = 1e-2
nx =  64
tstart = 32
tinterval = 10
g = 9.81
kappa = 0.2
dealias = 1.5
sensor_position = [3.5, 5.5, 7.5] # must remain in between xbounds
scenario = "waterchannel" #supported are waterchannel and periodic
bc_file = "./data/mean_bc.txt"
bathymetry = "exact_bathy" #supported are exact_bathy and gaussian

[sampler]
stepsize = [1.0, 0.1]
likelihood_var = 0.001
prior = "[Normal(4.5,1), Uniform(0, 2)]"
n_samples = 100
n_chains = 7
burn_in = 0
initial = [[6.0, 1.0], [5.0, 1.0], [4.0, 1.0], [3.0, 1.0], [2.5, 1.0], [5.5,1.0], [6.0,0.1]]

[observation]
#path = "./experiment_data/data_sensors/With_Bathymetry/Heat1.txt"
path = "./data/toy_measurement/waterchannel_exact_bathy"
real_data = false
noise_var = 0.05
sensor_rate = 0.01
sensor_pos = [3.5, 5.5, 7.5] # must remain in between xbounds

[output]
save = true
path = "./data/results"
