title = "MH Bathymetry Reco setup"

[simulation]
xbounds = [1.5, 15.0]
timestep = 1e-2
nx =  64
tstart = 32
tinterval = 10
g = 9.81
kappa = 0.2
dealias = 1.5
sensor_position = [3.5,5.5,7.5] # must remain in between xbounds
scenario = "waterchannel" #supported are waterchannel and periodic
bc_file = "./data/mean_bc.txt"
bathymetry = "exact_bathy" #supported are exact_bathy and gaussian

[sampler]
stepsize = [0.001]
likelihood_var = 0.001
n_samples = 10000
burn_in = 0
prior = "Normal{Float64}[Normal{Float64}(μ=4.0, σ=1.0), Normal{Float64}(μ=0.1, σ=0.1)]"
#[[6.0, 1.0], [5.0, 1.0], [4.0, 1.0], [3.0, 1.0], [2.5, 1.0], [5.5, 1.0], [6.0, 0.1]]
initial = []
n_chains = 1

[observation]
#path = "./data/experiment_data/data_sensors/With_Bathymetry/Heat1.txt"
path = "./data/toy_measurement/waterchannel_exact_bathy/"
real_data = false
noise_var = 0.05
sensor_rate = 0.01
sensor_id = [2,3,4] # Sensor IDs to use, must be in [2, 3, 4]

[output]
save = true
path = "./data/results"
