title = "MH Bathymetry Reco setup"

[simulation]
xbounds = [1.5, 15.0]
timestep = 1e-3
nx =  100
tstart = 32
tinterval = 10
g = 9.81
kappa = 0.2
dealias = 1.5
scenario = "waterchannel"
bathymetry = "exact_bathy"

[bathymetry]
parametrized = true
parameters = [3.5, 0.5]
npeaks = 1

[sampler]
parametrized = true
initial = [4.0, 1.0]
stepsize = [1.0, 0.1]
likelihood_var = 0.001
n_samples = 20
burnin = 0

[observation]
path = "./data/toy_measurement/"
noise_var = 0.0

[output]
save = true
path = "./data/results/experiment_"