title = "Toy Measurement Setup"

[output]
save = false
path = "./data/toy_measurement"

[simulation]
xbounds = [1.5, 15.0]
dealias = 1.5
scenario = "waterchannel"
nx = 64
timestep = 1e-2
kappa = 0.2
bathymetry = "exact_bathy"
sensor_position = [3.5, 5.5, 7.5]
tinterval = 10
g = 9.81
bc_file = "./data/mean_bc.txt"
tstart = 32

[bathymetry]
parameters = [4.0, 0.5]
npeaks = 1